package org.chappyGolf.model.cayenne.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.BaseProperty;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.chappyGolf.model.cayenne.Reservation;
import org.chappyGolf.model.cayenne.TeeTimeTier;

/**
 * Class _TeeTime was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TeeTime extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "id";

    public static final NumericProperty<Integer> CAPACITY = PropertyFactory.createNumeric("capacity", Integer.class);
    public static final BaseProperty<Boolean> RESERVED = PropertyFactory.createBase("reserved", Boolean.class);
    public static final DateProperty<LocalDateTime> SLOT = PropertyFactory.createDate("slot", LocalDateTime.class);
    public static final ListProperty<Reservation> RESERVATIONSS = PropertyFactory.createList("reservationss", Reservation.class);
    public static final EntityProperty<TeeTimeTier> TIER = PropertyFactory.createEntity("tier", TeeTimeTier.class);

    protected Integer capacity;
    protected Boolean reserved;
    protected LocalDateTime slot;

    protected Object reservationss;
    protected Object tier;

    public void setCapacity(int capacity) {
        beforePropertyWrite("capacity", this.capacity, capacity);
        this.capacity = capacity;
    }

    public int getCapacity() {
        beforePropertyRead("capacity");
        if(this.capacity == null) {
            return 0;
        }
        return this.capacity;
    }

    public void setReserved(Boolean reserved) {
        beforePropertyWrite("reserved", this.reserved, reserved);
        this.reserved = reserved;
    }

    public Boolean getReserved() {
        beforePropertyRead("reserved");
        return this.reserved;
    }

    public void setSlot(LocalDateTime slot) {
        beforePropertyWrite("slot", this.slot, slot);
        this.slot = slot;
    }

    public LocalDateTime getSlot() {
        beforePropertyRead("slot");
        return this.slot;
    }

    public void addToReservationss(Reservation obj) {
        addToManyTarget("reservationss", obj, true);
    }

    public void removeFromReservationss(Reservation obj) {
        removeToManyTarget("reservationss", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Reservation> getReservationss() {
        return (List<Reservation>)readProperty("reservationss");
    }

    public void setTier(TeeTimeTier tier) {
        setToOneTarget("tier", tier, true);
    }

    public TeeTimeTier getTier() {
        return (TeeTimeTier)readProperty("tier");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "capacity":
                return this.capacity;
            case "reserved":
                return this.reserved;
            case "slot":
                return this.slot;
            case "reservationss":
                return this.reservationss;
            case "tier":
                return this.tier;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "capacity":
                this.capacity = (Integer)val;
                break;
            case "reserved":
                this.reserved = (Boolean)val;
                break;
            case "slot":
                this.slot = (LocalDateTime)val;
                break;
            case "reservationss":
                this.reservationss = val;
                break;
            case "tier":
                this.tier = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.capacity);
        out.writeObject(this.reserved);
        out.writeObject(this.slot);
        out.writeObject(this.reservationss);
        out.writeObject(this.tier);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.capacity = (Integer)in.readObject();
        this.reserved = (Boolean)in.readObject();
        this.slot = (LocalDateTime)in.readObject();
        this.reservationss = in.readObject();
        this.tier = in.readObject();
    }

}
