package org.chappyGolf.model.cayenne.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.BaseProperty;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.chappyGolf.model.cayenne.Reservation;

/**
 * Class _TeeTime was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TeeTime extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "id";

    public static final BaseProperty<Boolean> BLOCKED = PropertyFactory.createBase("blocked", Boolean.class);
    public static final StringProperty<String> BLOCKED_REASON = PropertyFactory.createString("blockedReason", String.class);
    public static final NumericProperty<Integer> CAPACITY = PropertyFactory.createNumeric("capacity", Integer.class);
    public static final DateProperty<LocalDateTime> START_TIME = PropertyFactory.createDate("startTime", LocalDateTime.class);
    public static final ListProperty<Reservation> RESERVATIONS = PropertyFactory.createList("reservations", Reservation.class);

    protected boolean blocked;
    protected String blockedReason;
    protected Integer capacity;
    protected LocalDateTime startTime;

    protected Object reservations;

    public void setBlocked(boolean blocked) {
        beforePropertyWrite("blocked", this.blocked, blocked);
        this.blocked = blocked;
    }

	public boolean isBlocked() {
        beforePropertyRead("blocked");
        return this.blocked;
    }

    public void setBlockedReason(String blockedReason) {
        beforePropertyWrite("blockedReason", this.blockedReason, blockedReason);
        this.blockedReason = blockedReason;
    }

    public String getBlockedReason() {
        beforePropertyRead("blockedReason");
        return this.blockedReason;
    }

    public void setCapacity(Integer capacity) {
        beforePropertyWrite("capacity", this.capacity, capacity);
        this.capacity = capacity;
    }

    public Integer getCapacity() {
        beforePropertyRead("capacity");
        return this.capacity;
    }

    public void setStartTime(LocalDateTime startTime) {
        beforePropertyWrite("startTime", this.startTime, startTime);
        this.startTime = startTime;
    }

    public LocalDateTime getStartTime() {
        beforePropertyRead("startTime");
        return this.startTime;
    }

    public void addToReservations(Reservation obj) {
        addToManyTarget("reservations", obj, true);
    }

    public void removeFromReservations(Reservation obj) {
        removeToManyTarget("reservations", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Reservation> getReservations() {
        return (List<Reservation>)readProperty("reservations");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "blocked":
                return this.blocked;
            case "blockedReason":
                return this.blockedReason;
            case "capacity":
                return this.capacity;
            case "startTime":
                return this.startTime;
            case "reservations":
                return this.reservations;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "blocked":
                this.blocked = val == null ? false : (boolean)val;
                break;
            case "blockedReason":
                this.blockedReason = (String)val;
                break;
            case "capacity":
                this.capacity = (Integer)val;
                break;
            case "startTime":
                this.startTime = (LocalDateTime)val;
                break;
            case "reservations":
                this.reservations = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeBoolean(this.blocked);
        out.writeObject(this.blockedReason);
        out.writeObject(this.capacity);
        out.writeObject(this.startTime);
        out.writeObject(this.reservations);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.blocked = in.readBoolean();
        this.blockedReason = (String)in.readObject();
        this.capacity = (Integer)in.readObject();
        this.startTime = (LocalDateTime)in.readObject();
        this.reservations = in.readObject();
    }

}
