package org.chappyGolf.model.cayenne.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.chappyGolf.model.cayenne.TeeTime;

/**
 * Class _TeeTimeTier was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TeeTimeTier extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "id";

    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final NumericProperty<Long> PRICE_CENTS = PropertyFactory.createNumeric("priceCents", Long.class);
    public static final ListProperty<TeeTime> TEE_TIMES = PropertyFactory.createList("teeTimes", TeeTime.class);

    protected String name;
    protected long priceCents;

    protected Object teeTimes;

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setPriceCents(long priceCents) {
        beforePropertyWrite("priceCents", this.priceCents, priceCents);
        this.priceCents = priceCents;
    }

    public long getPriceCents() {
        beforePropertyRead("priceCents");
        return this.priceCents;
    }

    public void addToTeeTimes(TeeTime obj) {
        addToManyTarget("teeTimes", obj, true);
    }

    public void removeFromTeeTimes(TeeTime obj) {
        removeToManyTarget("teeTimes", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<TeeTime> getTeeTimes() {
        return (List<TeeTime>)readProperty("teeTimes");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "name":
                return this.name;
            case "priceCents":
                return this.priceCents;
            case "teeTimes":
                return this.teeTimes;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "name":
                this.name = (String)val;
                break;
            case "priceCents":
                this.priceCents = val == null ? 0 : (long)val;
                break;
            case "teeTimes":
                this.teeTimes = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.name);
        out.writeLong(this.priceCents);
        out.writeObject(this.teeTimes);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.name = (String)in.readObject();
        this.priceCents = in.readLong();
        this.teeTimes = in.readObject();
    }

}
