package org.chappyGolf.model.cayenne.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.chappyGolf.model.cayenne.Reservation;

/**
 * Class _Users was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Users extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "id";

    public static final DateProperty<LocalDateTime> CREATED_AT = PropertyFactory.createDate("createdAt", LocalDateTime.class);
    public static final StringProperty<String> EMAIL = PropertyFactory.createString("email", String.class);
    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final StringProperty<String> PASSWORD_HASH = PropertyFactory.createString("passwordHash", String.class);
    public static final StringProperty<String> ROLE = PropertyFactory.createString("role", String.class);
    public static final ListProperty<Reservation> RESERVATIONS = PropertyFactory.createList("reservations", Reservation.class);

    protected LocalDateTime createdAt;
    protected String email;
    protected String name;
    protected String passwordHash;
    protected String role;

    protected Object reservations;

    public void setCreatedAt(LocalDateTime createdAt) {
        beforePropertyWrite("createdAt", this.createdAt, createdAt);
        this.createdAt = createdAt;
    }

    public LocalDateTime getCreatedAt() {
        beforePropertyRead("createdAt");
        return this.createdAt;
    }

    public void setEmail(String email) {
        beforePropertyWrite("email", this.email, email);
        this.email = email;
    }

    public String getEmail() {
        beforePropertyRead("email");
        return this.email;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setPasswordHash(String passwordHash) {
        beforePropertyWrite("passwordHash", this.passwordHash, passwordHash);
        this.passwordHash = passwordHash;
    }

    public String getPasswordHash() {
        beforePropertyRead("passwordHash");
        return this.passwordHash;
    }

    public void setRole(String role) {
        beforePropertyWrite("role", this.role, role);
        this.role = role;
    }

    public String getRole() {
        beforePropertyRead("role");
        return this.role;
    }

    public void addToReservations(Reservation obj) {
        addToManyTarget("reservations", obj, true);
    }

    public void removeFromReservations(Reservation obj) {
        removeToManyTarget("reservations", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Reservation> getReservations() {
        return (List<Reservation>)readProperty("reservations");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "createdAt":
                return this.createdAt;
            case "email":
                return this.email;
            case "name":
                return this.name;
            case "passwordHash":
                return this.passwordHash;
            case "role":
                return this.role;
            case "reservations":
                return this.reservations;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "createdAt":
                this.createdAt = (LocalDateTime)val;
                break;
            case "email":
                this.email = (String)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "passwordHash":
                this.passwordHash = (String)val;
                break;
            case "role":
                this.role = (String)val;
                break;
            case "reservations":
                this.reservations = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.createdAt);
        out.writeObject(this.email);
        out.writeObject(this.name);
        out.writeObject(this.passwordHash);
        out.writeObject(this.role);
        out.writeObject(this.reservations);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.createdAt = (LocalDateTime)in.readObject();
        this.email = (String)in.readObject();
        this.name = (String)in.readObject();
        this.passwordHash = (String)in.readObject();
        this.role = (String)in.readObject();
        this.reservations = in.readObject();
    }

}
